### ISSUE TITLE
运行 win-image-matting-v0.1.1 程序报错

### ISSUE THREAD

**Issue by fsjoy52** [pangxiaobin/image-matting#1]
你好，感谢你提供的软件，效果不错。
但是，在Windows11 23H2(OS 内部版本 22631.3958)中运行 win-image-matting-v0.1.1 程序报错。
Failed to execute script 'main' due to unhandled exception: We couldn't connectto 'https://huggingface.co' to load this file, couldn't find it in the cached files andit looks like briaai/RMBG-1,4 is not the path to a directory containing a filenamed MyConfig.py.Checkout your internet connection or see how to run the library in offline modeat 'https://huggingface,co/docs/transformers/installation#offine-mode'.
![微信图片_20240729124445](https://github.com/user-attachments/assets/073af5cb-c66c-4b9d-8db4-83d6b7313760)
前一个版本 image-matting0.10 没有问题。

**Comment by pangxiaobin** [comment]
> 你好，感谢你提供的软件，效果不错。 但是，在Windows11 23H2(OS 内部版本 22631.3958)中运行 win-image-matting-v0.1.1 程序报错。 Failed to execute script 'main' due to unhandled exception: We couldn't connectto 'https://huggingface.co' to load this file, couldn't find it in the cached files andit looks like briaai/RMBG-1,4 is not the path to a directory containing a filenamed MyConfig.py.Checkout your internet connection or see how to run the library in offline modeat 'https://huggingface,co/docs/transformers/installation#offine-mode'. ![微信图片_20240729124445](https://private-user-images.githubusercontent.com/62759007/352916591-073af5cb-c66c-4b9d-8db4-83d6b7313760.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIyMzI2MzUsIm5iZiI6MTcyMjIzMjMzNSwicGF0aCI6Ii82Mjc1OTAwNy8zNTI5MTY1OTEtMDczYWY1Y2ItYzY2Yy00YjlkLThkYjQtODNkNmI3MzEzNzYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI5VDA1NTIxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNkNGY4NWYzOThjODcwZDhiNzAwMzg5ODM0MDYyYzVjODhjYjM2Yzc5ODViOWJmZWVmMTU3MzljMzAxOGFiMTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QgN21OcbdkRS08sQ3TZhCvT-ds5ohNIt4h9vN4OATzM) 前一个版本 image-matting0.10 没有问题。

看报错是模型没找到，你先开个梯子，应该会自动下载缓存模型，我看看是不是少打包东西了

**Comment by pangxiaobin** [comment]
已更新win 安装包

**Comment by fsjoy52** [comment]
> 已更新win 安装包

OK，已经正常工作，新增加的证件照功能很实用。我给你推广推广

**Comment by fsjoy52** [comment]
可能是因为模型本身的原因，抠图不干净或者边缘识别不是太精准。不过瑕不掩瑜，对于背景不是太复杂的图片出来的效果不错。
