### ISSUE TITLE
希望能支持AVIF格式图片转换

### ISSUE THREAD

**Issue by XZH2024** [pangxiaobin/image-matting#10]
希望能支持此格式

另外，我从官网的百度网盘渠道下载了Windows版的0.1.5版本，但是打开程序后显示的版本号却是0.1.4

**Comment by pangxiaobin** [comment]
有实现完善的转换工具，avif格式的支持就不实现了，目前py没有找到合适的库
推荐使用
https://www.nchsoftware.com/imageconverter/

https://avif2jpg.com/
