### ISSUE TITLE
0.1.2 Windows 版AI抠图图标链接有问题，显示不正常

### ISSUE THREAD

**Issue by fsjoy52** [pangxiaobin/image-matting#2]
![image](https://github.com/user-attachments/assets/4568e1ef-2b76-46ee-a4fb-298bd0441339)

0.1.2版AI抠图图标链接有问题，显示不正常；另外，我是 Windows 版本，Mac 版本不知道哈。
另外，图片格式转换最好能实现批量转换，不然要批量转换还要用类似 webp-converter 等单品，不能一个软件搞定。
当然，软件是你的作品，只是个人建议哈。

**Comment by pangxiaobin** [comment]
OK 我有空了更新下

**Comment by pangxiaobin** [comment]
已更新
