### ISSUE TITLE
Windows11下貌似运行不起来？

### ISSUE THREAD

**Issue by LuhangRui** [pangxiaobin/image-matting#4]
不知道是什么问题，这个打包应该会把python环境也打包进去的吧，双击运行之后没有任何反应，任务管理器里也没有找到相关进程。麻烦作者有时间的话帮忙看一下。

**Comment by pangxiaobin** [comment]
> 不知道是什么问题，这个打包应该会把python环境也打包进去的吧，双击运行之后没有任何反应，任务管理器里也没有找到相关进程。麻烦作者有时间的话帮忙看一下。

也没有报错提示吗，第一次加载会慢一些，或者可以先源码运行，我回头找个win11 系统试下。

**Comment by pangxiaobin** [comment]
找了个win11 测试了，可以运行的，可以自己源码运行试试。
