### ISSUE TITLE
Mac端下载下来打不开

### ISSUE THREAD

**Issue by spadeACE7** [pangxiaobin/image-matting#6]
mac端下载下来，解压后是一个文件夹，里面有个ImageMatting
是不是点击ImageMatting就可以了，但点击打开终端后没有任何效果了就

**Comment by pangxiaobin** [comment]
> mac端下载下来，解压后是一个文件夹，里面有个ImageMatting 是不是点击ImageMatting就可以了，但点击打开终端后没有任何效果了就

你的设备信息是什么
第一次加载会慢些，我目前手里的设备测试是没问题的，运行后应该会有个终端，有没有提示什么信息，或者看看_internal/log 看看有没有记录什么日志

**Comment by Jeason0228** [comment]
mac-binary-image-matting-v0.1.4解压后有一堆，，要怎么运行？ 双击ImageMatting后，会被安全拦截。解锁安全后仍然无法打开。求个桌面版吧
<img width="384" alt="image" src="https://github.com/user-attachments/assets/c223ff23-94d2-4350-b4cf-a3c3ecae136d">

**Comment by pangxiaobin** [comment]
> mac-binary-image-matting-v0.1.4解压后有一堆，，要怎么运行？ 双击ImageMatting后，会被安全拦截。解锁安全后仍然无法打开。求个桌面版吧 <img alt="image" width="384" src="https://private-user-images.githubusercontent.com/44083849/367165606-c223ff23-94d2-4350-b4cf-a3c3ecae136d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYyMDkyMzEsIm5iZiI6MTcyNjIwODkzMSwicGF0aCI6Ii80NDA4Mzg0OS8zNjcxNjU2MDYtYzIyM2ZmMjMtOTRkMi00MzUwLWI0Y2YtYTNjM2VjYWUxMzZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEzVDA2Mjg1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFiMTIzYjk4NmU1ZmY1ZjdhODg5ZDRmZDZkNzViZDAzZmZlMGQ4NTBkMjM5OWExNmVkOTk5ZDU0ZmZiYTFmZGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KspaL7SGWlapJdR1LwgQiQQjCiBp6ChhfKJj7RYgtA0">


https://matting.20133075.xyz/ 这里网盘里面有打包 app  解压后直接拖进应用就行。不同需要在安全与隐式-->  通用---> 允许任何来源  
这个设置后  点击ImageMatting 这个也可以运行的，第一次可能加载会慢些
<img width="294" alt="image" src="https://github.com/user-attachments/assets/1411c1f3-df92-421d-a6dd-75077dd4f48e">
